### ISSUE TITLE
add ability to pull linux files

### ISSUE THREAD

**Issue by xillwillx** [Static-Flow/CloudCopy#2]
not and issue but more of a feature addition, after mounting the snapshot have the option to pull linux files such as passwd/shadow files and any web config/db files

had used this on current pentest for a linux box and just added a input() right above the cleanup portion to keep the instance from terminating so i could grab files 

other than that everything worked perfectly :)

**Comment by Static-Flow** [comment]
I thought about doing this initially, having the cleanup be its own command, so the user could determine when they wanted to cleanup. I'll certainly add the /etc/shadow /etc/passwd. In version two I'm going to modularize it so people can plug and play different attacks like grabbing web.config files, etc.

Thank you for suggestion and I'm glad it worked so well!

**Comment by xillwillx** [comment]
nice, yea def something to ask would work, instead of automatically terminating the instance because you cant get it back. just in case you wanted to grab other data from the box
